// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANr_97GpKbCNzI-x3M4esxbsUY8RQv-mQ',
    appId: '1:798327527205:web:dce7d3647b5596dd8eaccc',
    messagingSenderId: '798327527205',
    projectId: 'final-nowar',
    authDomain: 'final-nowar.firebaseapp.com',
    storageBucket: 'final-nowar.appspot.com',
    measurementId: 'G-LFEKKVYR6P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcWa2Y0dmiCfVBKrI1LpY0HHJIG3l40TY',
    appId: '1:798327527205:android:eb63596e5bbc6e9c8eaccc',
    messagingSenderId: '798327527205',
    projectId: 'final-nowar',
    storageBucket: 'final-nowar.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCO-LaUD0w3QOoNctUbdOlkvIjmdxJ-Xho',
    appId: '1:798327527205:ios:e4c3389f5557b8d28eaccc',
    messagingSenderId: '798327527205',
    projectId: 'final-nowar',
    storageBucket: 'final-nowar.appspot.com',
    iosBundleId: 'com.example.noWar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCO-LaUD0w3QOoNctUbdOlkvIjmdxJ-Xho',
    appId: '1:798327527205:ios:327ca178054ae4cd8eaccc',
    messagingSenderId: '798327527205',
    projectId: 'final-nowar',
    storageBucket: 'final-nowar.appspot.com',
    iosBundleId: 'com.example.noWar.RunnerTests',
  );
}
